### ISSUE TITLE
Tryna understand basics

### ISSUE THREAD

**Issue by amanbagrecha** [amanbagrecha/github-slideshow#4] opened 2020-12-21 12:25 UTC
when do you issue issue? before branching or after it

**Comment by concretefair** [comment] 2020-12-21 12:36
Issues have nothing to do with braching maccha @amanbagrecha 💯

**Comment by amanbagrecha** [comment] 2020-12-21 12:37
#3 was done to justify the commit

- [x] did you learn something!?
- [ ] `does this help?`

**Comment by concretefair** [comment] 2020-12-21 12:40
> #3 was done to justify the commit
> 
> * [x]  did you learn something!?
> * [ ]  `does this help?`

Yes I did maccha
![Uploading myAvatar.png…]()

**Comment by concretefair** [comment] 2020-12-21 12:43
Duplicate of #1

**Comment by amanbagrecha** [comment] 2020-12-22 14:33
enjoyed a lot!

**Closed as completed** 2020-12-22 14:32 UTC
